/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProxyHttpRouteImport } from './routes/api/public/proxy-http'
import { Route as ApiPublicProxyWsRouteImport } from './routes/api/public/proxy-ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyHttpRoute = ApiPublicProxyHttpRouteImport.update({
  id: '/api/public/proxy-http',
  path: '/api/public/proxy-http',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyWsRoute = ApiPublicProxyWsRouteImport.update({
  id: '/api/public/proxy-ws',
  path: '/api/public/proxy-ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/proxy-http': typeof ApiPublicProxyHttpRoute
  '/api/public/proxy-ws': typeof ApiPublicProxyWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/proxy-http': typeof ApiPublicProxyHttpRoute
  '/api/public/proxy-ws': typeof ApiPublicProxyWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/proxy-http': typeof ApiPublicProxyHttpRoute
  '/api/public/proxy-ws': typeof ApiPublicProxyWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/proxy-http' | '/api/public/proxy-ws'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/proxy-http' | '/api/public/proxy-ws'
  id: '__root__' | '/' | '/api/public/proxy-http' | '/api/public/proxy-ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicProxyHttpRoute: typeof ApiPublicProxyHttpRoute
  ApiPublicProxyWsRoute: typeof ApiPublicProxyWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy-http': {
      id: '/api/public/proxy-http'
      path: '/api/public/proxy-http'
      fullPath: '/api/public/proxy-http'
      preLoaderRoute: typeof ApiPublicProxyHttpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy-ws': {
      id: '/api/public/proxy-ws'
      path: '/api/public/proxy-ws'
      fullPath: '/api/public/proxy-ws'
      preLoaderRoute: typeof ApiPublicProxyWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicProxyHttpRoute: ApiPublicProxyHttpRoute,
  ApiPublicProxyWsRoute: ApiPublicProxyWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
